version: "3.6"

services:
  db:
    image: postgres
    container_name: workoutapp_db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: workoutapp
    volumes:
      - dbdata:/var/lib/postgresql/data

  adm:
    image: dpage/pgadmin4
    container_name: workoutapp_dbadm
    ports:
      - 8081:80
    environment:
      PGADMIN_DEFAULT_EMAIL: leon@gmail.com
      PGADMIN_DEFAULT_PASSWORD: user
    volumes:
      - admdata:/var/lib/pgadmin

volumes:
  dbdata:
  admdata: