INSERT INTO public.exercise(category, created_at, name) 
VALUES 
('STR' , NOW(), 'Bench press'),
('STR' , NOW(), 'Deadlift'),
('STR' , NOW(), 'Overhead press'),
('STR' , NOW(), 'Squat'),
('BW' , NOW(), 'Bodyweight squat'),
('BW' , NOW(), 'Pistol squat'),
('BW' , NOW(), 'Shrimp squat'),
('BW' , NOW(), 'Pull up'),
('STR' , NOW(), 'Weighted pull up'),
('BW' , NOW(), 'Handstand push up'),
('BW' , NOW(), 'Sitting leg raise'),
('BW' , NOW(), 'Hanging leg raise'),
('BW' , NOW(), 'Push up'),
('BW' , NOW(), 'Diamond push up'),
('BW' , NOW(), 'One handed push up'),
('BW' , NOW(), 'Incline one handed push up'),
('BW' , NOW(), 'Assisted one handed push up'),
('BW' , NOW(), 'Inverted rows'),
('BW' , NOW(), 'Front lever tuck rows'),
('TIM' , NOW(), 'Plank'),
('CA' , NOW(), 'Hill walking'),
('CA' , NOW(), 'Stationary bike'),
('CA' , NOW(), 'Jogging'),
('ST' , NOW(), 'Quad stretch'),
('ST' , NOW(), 'Hamstring stretch');